### ISSUE TITLE
Pages like the one for G.I. Bill

### ISSUE THREAD

**Issue by sgbasaraner** [halileohalilei/ZeroWiki#6]
When given this URL "https://en.wikipedia.org/wiki/G.I._Bill", the extension loads this page: "http://www.wiki-zero.com/index.php?q=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvRw", which is the page for the letter G in wikipedia. I don't believe this issue stems from the extension, as https://en.0wikipedia.org/wiki/G.I._Bill also gives the same page. However, the reason behind the misfunction could be investigated and be fixed in extension level. I can also contact ZeroWiki themselves if you think it's more appropriate.

**Comment by halileohalilei** [comment]
Hey @sgbasaraner, thank you for the issue. I am aware of this problem as it was mentioned by a couple more people. As you said it though, the problem stems from the 0wikipedia mirror itself, and there isn't much I can do. As I understood from the URL 0wikipedia redirects to, every page has a unique hash code, and I don't think there is a way to infer the hash code of an arbitrary page without actually seeing the source code for 0wikipedia.

One solution I was thinking of was to redirect to one of the other mirrors if the URL contains one of the characters that break 0wikipedia. 

You can contact the developers of 0wikipedia (and so will I), telling them about the issue. I'm pretty sure they are already aware of it but more reports mean faster resolution. In the meantime, you can use one of the other mirrors available on ZeroWiki, since only 0wikipedia has this problem.

**Comment by halileohalilei** [comment]
Hey @sgbasaraner, I contacted the developers and it seems they've fixed it. Cheers.
